language: c

compiler:
  - gcc
  - clang

cache:
  directories:
    - usr

install:
    - git clone https://github.com/huitema/picotls.git
    - cd picotls
    - git checkout cmake-install-lib
    - git submodule init
    - git submodule update
    - cmake .
    - make
    - make DESTDIR=$(pwd)/../ install
    - cd ..
    - git clone https://github.com/private-octopus/picoquic.git
    - cd picoquic
    - cmake .
    - make
    - make DESTDIR=$(pwd)/../ install
    -  cd ..
  
script:
  - ./autogen.sh
  - export LD_LIBRARY_PATH=$(pwd)/usr/local/lib/:$LD_LIBRARY_PATH
  - ls usr/local/
  - ls usr/local/lib
  - ./configure CFLAGS=-I$(pwd)/usr/local/include/
  - make
