name: C/C++ CI

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: picotls
      run: |
        git clone https://github.com/huitema/picotls.git ../picotls
        cd ../picotls
        git submodule init
        git submodule update
        cmake .
        make
        cd $GITHUB_WORKSPACE
    - name: rapido
      run: |
        git clone https://github.com/mpiraux/rapido.git ../rapido
        cd ../rapido
        git submodule init
        git submodule update
        cmake .
        make
        cd $GITHUB_WORKSPACE
    - name: picoquic
      run: |
        git clone https://github.com/private-octopus/picoquic.git ../picoquic
        cd ../picoquic
        cmake .
        make
        cd $GITHUB_WORKSPACE
    - name: build
      run: |
        ./autogen.sh
        ./configure
        make
